version: '3'

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=starter
      - POSTGRES_USER=starter
      - POSTGRES_PASSWORD=starter
    # volumes:
    #   - ./data/postgres:/var/lib/postgresql/data
  
  redis:
    image: redis:latest
    # volumes:
    #   - ./data/redis:/data

  migration:
    build: .
    depends_on:
      - postgres
      - redis
    command: ['python3', 'manage.py', 'migrate']
    links:
      - postgres:postgres
      - redis:redis

  worker:
    build: .
    depends_on:
      - postgres
      - redis
    command: ['celery', '-A', 'starter', 'worker', '-l', 'info'] # celery -A starter worker -l info
    links:
      - postgres:postgres
      - redis:redis

  beat:
    build: .
    depends_on:
      - postgres
      - redis
      - web
    command: ['celery', '-A', 'starter', 'beat', '-l', 'info', '-S', 'django'] # celery -A proj beat -l info -S django
    links:
      - postgres:postgres
      - redis:redis

  web:
    build: .
    depends_on:
      - postgres
      - redis
      - migration
    command: ['gunicorn', 'starter.wsgi', '--bind', '0.0.0.0:80']
    ports:
      - 80:80
    links:
      - postgres:postgres
      - redis:redis